version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: pharmforge-db
    environment:
      POSTGRES_USER: pharmforge
      POSTGRES_PASSWORD: pharmforge_dev_password
      POSTGRES_DB: pharmforge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmforge"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: pharmforge-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pharmforge-backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://pharmforge:pharmforge_dev_password@postgres:5432/pharmforge
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app/backend
      - ./adapters:/app/adapters
      - ./config:/app/config
      - cache_data:/app/cache

  # Celery Worker
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pharmforge-celery-worker
    command: celery -A backend.celery_app worker --loglevel=info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://pharmforge:pharmforge_dev_password@postgres:5432/pharmforge
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app/backend
      - ./adapters:/app/adapters
      - ./config:/app/config
      - cache_data:/app/cache

volumes:
  postgres_data:
  redis_data:
  cache_data:
