"""Initial schema

Revision ID: 0ea866625d16
Revises: 
Create Date: 2025-10-24 13:01:41.459039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea866625d16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('adapter_type', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapters_id'), 'adapters', ['id'], unique=False)
    op.create_index(op.f('ix_adapters_name'), 'adapters', ['name'], unique=True)
    op.create_table('cache_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=256), nullable=False),
    sa.Column('adapter_name', sa.String(length=64), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_entries_adapter_name'), 'cache_entries', ['adapter_name'], unique=False)
    op.create_index(op.f('ix_cache_entries_cache_key'), 'cache_entries', ['cache_key'], unique=True)
    op.create_index(op.f('ix_cache_entries_id'), 'cache_entries', ['id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_smiles', sa.JSON(), nullable=False),
    sa.Column('pipeline_config', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('lockfile', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_run_id'), 'pipeline_runs', ['run_id'], unique=True)
    op.create_table('compound_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('smiles', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('bioactivity', sa.JSON(), nullable=True),
    sa.Column('admet', sa.JSON(), nullable=True),
    sa.Column('docking', sa.JSON(), nullable=True),
    sa.Column('synthesis', sa.JSON(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compound_results_compound_id'), 'compound_results', ['compound_id'], unique=False)
    op.create_index(op.f('ix_compound_results_id'), 'compound_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compound_results_id'), table_name='compound_results')
    op.drop_index(op.f('ix_compound_results_compound_id'), table_name='compound_results')
    op.drop_table('compound_results')
    op.drop_index(op.f('ix_pipeline_runs_run_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_cache_entries_id'), table_name='cache_entries')
    op.drop_index(op.f('ix_cache_entries_cache_key'), table_name='cache_entries')
    op.drop_index(op.f('ix_cache_entries_adapter_name'), table_name='cache_entries')
    op.drop_table('cache_entries')
    op.drop_index(op.f('ix_adapters_name'), table_name='adapters')
    op.drop_index(op.f('ix_adapters_id'), table_name='adapters')
    op.drop_table('adapters')
    # ### end Alembic commands ###
